server {
    listen 80;
    server_name localhost; # 容器內部用 localhost 即可

    root /usr/share/nginx/html;
    index index.html;

    client_max_body_size 10m;

    # 容器內只需要留下這一個區塊，用來正確渲染前端 React/Vue 的路由
    location / {
        try_files $uri $uri/ /index.html;
    }
}