# Generated by Django 6.0.5 on 2026-05-14 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_room_code_room_created_at_roommember'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='passwordresetcode',
            new_name='password_re_email_c29bfe_idx',
            old_name='password_re_email_token_idx',
        ),
    ]
