# Generated by Django 6.0.5 on 2026-05-14 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_matchmakingticket_roommember_ai'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='matchmakingticket',
            new_name='matchmaking_status_863774_idx',
            old_name='matchmaking_status_6f9e7d_idx',
        ),
    ]
