# Generated by Django 6.0.6 on 2026-06-07 04:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_rename_matchmaking_status_6f9e7d_idx_matchmaking_status_863774_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='matchmakingticket',
            name='source_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_matchmaking_tickets', to='game.room'),
        ),
        migrations.AddIndex(
            model_name='matchmakingticket',
            index=models.Index(fields=['status', 'source_room', 'created_at'], name='matchmaking_status_9bec50_idx'),
        ),
    ]
